name = "FerriteNODGrid"
uuid = "570c3397-5fe4-4792-be0d-48dbf0d14605"
authors = ["Dennis Ogiermann"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
