export
    # ---- User facing ----
    # AbstractNODGrid,
    NODGrid,
    generate_nod_grid,
    create_partitioning,
    vtk_shared_edges,
    vtk_shared_faces,
    vtk_shared_vertices,
    vtk_partitioning,
    # ----    Utils    ----
    # global_comm,
    # interface_comm,
    # global_rank,
    compute_owner,
    get_shared_vertices,
    get_shared_vertex,
    get_shared_edges,
    get_shared_edge,
    get_shared_faces,
    get_shared_face,
    is_shared_vertex,
    is_shared_edge,
    is_shared_face,
    getlocalgrid,
    #
    face_dofs,
    has_face_dofs,
    vertex_dofs,
    has_vertex_dofs,
    cell_dofs,
    has_cell_dofs,
    edge_dofs,
    has_edge_dofs
