name: CI

on:
  pull_request:
  push:
    branches: master
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1.9', 'nightly']
        os: ['ubuntu-latest']
        include:
          - os: windows-latest
            julia-version: '1.9'
          - os: macOS-latest
            julia-version: '1.9'
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.add(url="https://github.com/Ferrite-FEM/Ferrite.jl.git", rev="7e8a571"); Pkg.instantiate(); Pkg.precompile()'
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: 'src,ext'
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/packages
            ~/.julia/registries
          key: .julia-docs-${{ hashFiles('docs/Project.toml', 'docs/Manifest.toml') }}
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.add(url="https://github.com/Ferrite-FEM/Ferrite.jl.git", rev="7e8a571"); Pkg.instantiate(); Pkg.precompile()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GKSwstype: '100'
        run: julia --project=docs --color=yes docs/make.jl
