name: CI

on:
  pull_request:
  push:
    branches: main
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1.9']
        os: ['ubuntu-latest']
        include:
          - os: macOS-latest
            julia-version: '1.9'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.add(url="https://github.com/Ferrite-FEM/Ferrite.jl.git", rev="7e8a571"); Pkg.precompile()'
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: 'src,ext'
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info

