name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/packages
            ~/.julia/registries
          key: .julia-docs-${{ hashFiles('docs/Project.toml', 'docs/Manifest.toml') }}
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(url="https://github.com/Ferrite-FEM/Ferrite.jl.git", rev="7e8a571"); Pkg.precompile()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GKSwstype: '100'
        run: julia --project=docs --color=yes docs/make.jl
